#!/usr/bin/env python3
"""
Part 2: images-list-to4up-latex.py

Generic image lister to 4-up LaTeX converter.
Reads image paths from stdin (or file), one per line.
Generates 4-up LaTeX pages with labels and hyperref support.

Input format: one path per line
  orig-files-proc/iran-cia-intro/page_1.png
  orig-files-proc/iran-cia-intro/page_2.png
  ...

Label derivation:
  From path: orig-files-proc/iran-cia-intro/page_1.png
  Extract ending: iran-cia-intro/page_1.png
  Derive label: img:iran-cia-intro:page_1

Output: LaTeX include content for 4-up pages (8.5x11)

Usage:
  cat imagelist.txt | python images-list-to4up-latex.py > output.tex
  iran-cia-images-list.py | python images-list-to4up-latex.py > output.tex
  python images-list-to4up-latex.py --input imagelist.txt --output output.tex
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert image list to 4-up LaTeX pages."
    )
    parser.add_argument(
        "--input",
        type=str,
        default=None,
        help="Input file with image paths (default: stdin).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output file (default: stdout).",
    )
    return parser.parse_args()


def extract_ending(path_str: str) -> str:
    """
    Extract the ending part of path after the first component.
    Examples:
      orig-files-proc/iran-cia-intro/page_1.png → iran-cia-intro/page_1.png
      some-prefix/foo/bar/baz.png → foo/bar/baz.png
    """
    parts = path_str.split("/")
    if len(parts) > 1:
        return "/".join(parts[1:])
    return path_str


def derive_label(ending: str) -> str:
    """
    Derive label from the ending path.
    Example:
      iran-cia-intro/page_1.png → img:iran-cia-intro:page_1
    """
    p = Path(ending)
    section_dir = p.parent.name
    page_stem = p.stem
    return f"img:{section_dir}:{page_stem}"


def render_cell(image_path: str, label: str, fit_width: str = "0.48\\textwidth",
                fit_height: str = "0.45\\textheight") -> str:
    """Render a single image cell with label and includegraphics."""
    return (
        f"\\phantomsection\\label{{{label}}}%\n"
        f"\\includegraphics[width={fit_width},height={fit_height},keepaspectratio]{{{image_path}}}"
    )


def render_page_4up(items: List[str]) -> List[str]:
    """
    Render one 4-up page from a list of image paths (1-4 items).
    Each item is the full path: orig-files-proc/iran-cia-intro/page_1.png
    """
    cells: List[str] = []
    for image_path in items:
        ending = extract_ending(image_path)
        label = derive_label(ending)
        cells.append(render_cell(image_path, label))

    # Pad incomplete last page
    while len(cells) < 4:
        cells.append("\\mbox{}")

    lines: List[str] = [
        "\\begin{center}",
        "\\setlength{\\tabcolsep}{0pt}",
        "\\renewcommand{\\arraystretch}{1.0}",
        "\\begin{tabular}{|c|c|}",
        "\\hline",
        f"{cells[0]} & {cells[1]} \\\\\\hline",
        f"{cells[2]} & {cells[3]} \\\\\\hline",
        "\\end{tabular}",
        "\\end{center}",
        "\\clearpage",
    ]
    return lines


def main() -> int:
    args = parse_args()

    # Read input
    if args.input:
        try:
            input_file = Path(args.input)
            input_text = input_file.read_text(encoding="utf-8")
        except Exception as e:
            print(f"✗ Error reading input file: {e}", file=sys.stderr)
            return 1
    else:
        input_text = sys.stdin.read()

    # Parse paths
    paths = [line.strip() for line in input_text.strip().split("\n") if line.strip()]

    if not paths:
        print("✗ Error: no image paths found in input", file=sys.stderr)
        return 1

    # Generate LaTeX
    lines: List[str] = [
        "% Auto-generated by images-list-to4up-latex.py",
        "% Layout: 4 images per LaTeX page (8.5x11)",
        "%",
        "% Label format: img:<section>:<stem>  e.g. img:iran-cia-intro:page_1",
        "% Use \\pageref{img:iran-cia-intro:page_1} to reference by PDF page number",
        "",
    ]

    # Process paths in groups of 4
    for i in range(0, len(paths), 4):
        group = paths[i : i + 4]
        lines.extend(render_page_4up(group))
        lines.append("")

    output_text = "\n".join(lines).rstrip() + "\n"

    # Write output
    if args.output:
        output_file = Path(args.output)
        output_file.write_text(output_text, encoding="utf-8")
        page_count = (len(paths) + 3) // 4
        print(f"✓ Wrote {output_file}", file=sys.stderr)
        print(f"  - input images: {len(paths)}", file=sys.stderr)
        print(f"  - generated LaTeX pages: {page_count}", file=sys.stderr)
    else:
        sys.stdout.write(output_text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
